services:
  - type: web
    name: foodlink-connect
    region: oregon
    plan: free
    env: nixpacks
    buildCommand: ""
    startCommand: "gunicorn run:app"
    nixpacksConfig:
      phases:
        install:
          aptPkgs:
            - python3.11
            - python3.11-venv
            - python3.11-dev
      nodejs: false
      pythonVersion: "3.11"
